spring:
  application:
    name: reservation-service
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
